# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.4.4"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
wally = "upliftGames/wally@0.3.2"
darklua = "seaofvoices/darklua@0.14.0"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.2"
stylua = "JohnnyMorganz/StyLua@2.0.1"
